name: Update badges

on:
  schedule:
    # Runs at 0:15am UTC every day
    - cron: "15 0 * * *"
  workflow_dispatch:
permissions:
  contents: write # To write the generated contents to the readme
  
jobs:
  update-readme:
    name: Update Readme with badges
    runs-on: ubuntu-latest
    steps:
      - name: Badges - Readme
        uses: pemtajo/badge-readme@main
        with:       
          CREDLY_USER: claude-b
          
      - name: Testing the feed
        run: curl -I https://cybermonkey.me/feed.xml

      - name: Checkout
        uses: actions/checkout@v4
        continue-on-error: true
        with:
          fetch-depth: 0
          persist-credentials: true
          set-safe-directory: true
          submodules: 'recursive'
          clean: true
        
      - name: Pull in posts
        uses: gautamkrishnar/blog-post-workflow@1.8.8
        with:
          feed_list: "https://cybermonkey.me/feed.xml"
          
