name: Update badges

on:
  schedule:
    # Runs at 0:15am UTC every day
    - cron: "15 0 * * *"
  workflow_dispatch:
    
jobs:
  update-readme:
    name: Update Readme with badges
    runs-on: ubuntu-latest
    steps:
      - name: Badges - Readme
        uses: pemtajo/badge-readme@main
        with:       
          CREDLY_USER: claude-b
      - name: Pull in posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://pencer.io/feed.xml"
          max_post_count: 5
          
